### ISSUE TITLE
No CUDA GPUs are available

### ISSUE THREAD

**Issue by dsaffggerw** [PozzettiAndrea/ComfyUI-MotionCapture#42]
The following error occurred when running GVHMR on the WSL ubuntu:
```
!!! Exception during processing !!! No CUDA GPUs are available

Worker traceback:
Traceback (most recent call last):
  File "/tmp/comfyui_pvenv_9j4mbw4u/persistent_worker.py", line 1143, in main
    result = method(**inputs)
             ^^^^^^^^^^^^^^^^
  File "/home/abc/ComfyUI/custom_nodes/comfyui-motioncapture/nodes/inference_node.py", line 760, in run_inference
    import comfy.model_management
  File "/home/abc/ComfyUI/comfy/model_management.py", line 256, in <module>
    total_vram = get_total_memory(get_torch_device()) / (1024 * 1024)
                                  ^^^^^^^^^^^^^^^^^^
  File "/home/abc/ComfyUI/comfy/model_management.py", line 206, in get_torch_device
    return torch.device(torch.cuda.current_device())
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/abc/ComfyUI/custom_nodes/comfyui-motioncapture/nodes/_env_3d7791/lib/python3.11/site-packages/torch/cuda/__init__.py", line 1071, in current_device
    _lazy_init()
  File "/home/abc/ComfyUI/custom_nodes/comfyui-motioncapture/nodes/_env_3d7791/lib/python3.11/site-packages/torch/cuda/__init__.py", line 412, in _lazy_init
    torch._C._cuda_init()
RuntimeError: No CUDA GPUs are available

Traceback (most recent call last):
  File "/home/abc/ComfyUI/execution.py", line 524, in execute
    output_data, output_ui, has_subgraph, has_pending_tasks = await get_output_data(prompt_id, unique_id, obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb, v3_data=v3_data)
                                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/abc/ComfyUI/execution.py", line 333, in get_output_data
    return_values = await _async_map_node_over_list(prompt_id, unique_id, obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb, v3_data=v3_data)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/abc/ComfyUI/execution.py", line 307, in _async_map_node_over_list
    await process_inputs(input_dict, i)
  File "/home/abc/ComfyUI/execution.py", line 295, in process_inputs
    result = f(**inputs)
             ^^^^^^^^^^^
  File "/home/abc/ComfyUI/.venv/lib/python3.12/site-packages/comfy_env/isolation/metadata.py", line 352, in proxy
    result = worker.call_method(
             ^^^^^^^^^^^^^^^^^^^
  File "/home/abc/ComfyUI/.venv/lib/python3.12/site-packages/comfy_env/isolation/workers/subprocess.py", line 2376, in call_method
    raise WorkerError(
comfy_env.isolation.workers.base.WorkerError: No CUDA GPUs are available

Worker traceback:
Traceback (most recent call last):
  File "/tmp/comfyui_pvenv_9j4mbw4u/persistent_worker.py", line 1143, in main
    result = method(**inputs)
             ^^^^^^^^^^^^^^^^
  File "/home/abc/ComfyUI/custom_nodes/comfyui-motioncapture/nodes/inference_node.py", line 760, in run_inference
    import comfy.model_management
  File "/home/abc/ComfyUI/comfy/model_management.py", line 256, in <module>
    total_vram = get_total_memory(get_torch_device()) / (1024 * 1024)
                                  ^^^^^^^^^^^^^^^^^^
  File "/home/abc/ComfyUI/comfy/model_management.py", line 206, in get_torch_device
    return torch.device(torch.cuda.current_device())
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/abc/ComfyUI/custom_nodes/comfyui-motioncapture/nodes/_env_3d7791/lib/python3.11/site-packages/torch/cuda/__init__.py", line 1071, in current_device
    _lazy_init()
  File "/home/abc/ComfyUI/custom_nodes/comfyui-motioncapture/nodes/_env_3d7791/lib/python3.11/site-packages/torch/cuda/__init__.py", line 412, in _lazy_init
    torch._C._cuda_init()
RuntimeError: No CUDA GPUs are available
```

**Comment by PozzettiAndrea** [comment]
Hi @dsaffggerw Do you own an nvidia GPU? otherwise it might be the case that wsl is not set up to access it. What is your GPU model? :)

**Comment by wfox4** [comment]
If you're not using a nvidia gpu, You can try activating the comfy env and installing all the pypi-dependencies inside the comfy-env.toml file in the comfyui install-> custom_nodes\comfyui-motioncapture\nodes folder. I was able to get it to work by just doing this while using an Intel B70, Im assuming amd might be just as easy

<img width="688" height="365" alt="Image" src="https://github.com/user-attachments/assets/edaec7b9-6c15-4765-b7e3-518622247bae" />

<img width="1277" height="1293" alt="Image" src="https://github.com/user-attachments/assets/1b6a58b4-641a-414f-9e0f-d00704ba9112" />
